// <auto-generated />
using Bolnica_back.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bolnica_back.Migrations
{
    [DbContext(typeof(BolnicaContext))]
    [Migration("20210106232850_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Bolnica_back.Models.Bolnica", b =>
                {
                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IME");

                    b.HasKey("Ime");

                    b.ToTable("BolnicaPodaci");
                });

            modelBuilder.Entity("Bolnica_back.Models.Odeljenje", b =>
                {
                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IME");

                    b.Property<string>("BolnicaIme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BrojKreveta")
                        .HasColumnType("int")
                        .HasColumnName("BROJ_KREVETA");

                    b.Property<int>("BrojZauzetihKreveta")
                        .HasColumnType("int")
                        .HasColumnName("BROJ_ZAUZETIH_KREVETA");

                    b.HasKey("Ime");

                    b.HasIndex("BolnicaIme");

                    b.ToTable("OdeljenjePodaci");
                });

            modelBuilder.Entity("Bolnica_back.Models.Odeljenje", b =>
                {
                    b.HasOne("Bolnica_back.Models.Bolnica", "Bolnica")
                        .WithMany("Odeljenja")
                        .HasForeignKey("BolnicaIme");

                    b.Navigation("Bolnica");
                });

            modelBuilder.Entity("Bolnica_back.Models.Bolnica", b =>
                {
                    b.Navigation("Odeljenja");
                });
#pragma warning restore 612, 618
        }
    }
}
